#_format_version: "3.0"
#_transform: true
#
#services:
#  - name: auth-service
#    # url: http://172.18.0.5:9811
#    url: http://auth-service:9811
#    # since we have connecting every services under the same network we can use the container name instead of ip and moreover on every restart the ip of the container may change so it is not a good practice have the ip
#    routes:
#      - name: sign-up
#        paths:
#          - /auth/v1
#  - name: user-service
#    # url: http://172.18.0.6:9810
#    url: http://user-service:9810
#    routes:
#      - name: get-user
#        paths:
#          - /users/v1
## plugins:
##   - name: jwt
##     service: auth-service
##   - name: jwt
##     service: auth-service
##   - name: key-auth
##   - name: acl
#
#


_format_version: "2.1"
_transform: true

services:
  - name: expense-service
    url: http://expense-service:9820
    routes:
      - name: expense-route
        paths:
          - /expense/v1
        strip_path: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: http://auth-service:9811/auth/v1/ping

  - name: user-service
    url: http://user-service:9810
    routes:
      - name: user-route
        paths:
          - /users/v1
        strip_path: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: http://auth-service:9811/auth/v1/ping

  - name: ds-service
    url: http://ds-service:8010
    routes:
      - name: ds-route
        paths:
          - /v1/ds
        strip_path: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: http://auth-service:9811/auth/v1/ping

  - name: auth-service
    url: http://auth-service:9811
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: false
        preserve_host: false
